backups/urls.py
from django.urls import path

from . import views

app_name = "backups"

urlpatterns = [
    # Backup Views
    path(route='', view=views.BackupListView.as_view(), name='backup_list'),
    path(route='add/', view=views.BackupCreateView.as_view(), name='backup_add'),
    path(route='restore/', view=views.RestoreView.as_view(), name='backup_restore'),
    path(route='view/<int:pk>/', view=views.BackupDetailView.as_view(), name='backup_detail'),
    path(route='delete/<int:pk>/', view=views.BackupDeleteView.as_view(), name='backup_delete'),
    path(route='download/<int:pk>/', view=views.BackupDownloadView.as_view(), name='backup_download'),
    # path(route='update/<slug:slug>/', view=views.BackupUpdateView.as_view(), name='backup_update'),

]

fermentrack_django/urls.py
from django.conf.urls import url
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

import app.views
import app.profile_views
import app.setup_views
import app.beer_views
import app.api.lcd
import app.api.clog
import app.api.devices

import firmware_flash.urls
import gravity.urls
import external_push.urls

admin.autodiscover()

# In addition to urlpatterns below, three paths are mapped by the nginx config file:
# r'^static/' - Maps to collected_static/. Contains collected static files.
# r'^media/' - Maps to media/. Contains uploaded files. Currently unused.
# r'^data/' - Maps to data/. Contains data points collected by brewpi.py.

# Separately, all r'^firmware/' urls are contained in firmware_flash/urls.py

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', app.views.siteroot, name='siteroot'),

    url(r'^upgrade/$', app.views.github_trigger_upgrade, name='github_trigger_upgrade'),
    # url(r'^upgrade/force/$', app.views.github_trigger_force_upgrade, name='github_trigger_force_upgrade'),
    # url(r'^upgrade/delete_lock/$', app.views.delete_upgrade_lock_file, name='delete_upgrade_lock_file'),

    ### Device Views
    url(r'^devices/$', app.views.device_lcd_list, name='device_lcd_list'),
    url(r'^devices/add/$', app.views.add_device, name='device_add'),

    ## New install Guided Setup Views
    url(r'^setup/$', app.setup_views.setup_splash, name="setup_splash"),
    url(r'^setup/add_user/$', app.setup_views.setup_add_user, name="setup_add_user"),
    url(r'^setup/settings/$', app.setup_views.setup_config, name="setup_config"),  # This is settings.CONSTANCE_SETUP_URL

    ## Device Guided Setup Views
    url(r'^devices/guided/$', app.setup_views.device_guided_select_device, name='device_guided_select_device'),
    url(r'^devices/guided/(?P<device_family>[A-Za-z0-9]{1,20})/flash_prompt/$', app.setup_views.device_guided_flash_prompt, name='device_guided_flash_prompt'),
    url(r'^devices/guided/(?P<device_family>[A-Za-z0-9]{1,20})/flash/$', app.setup_views.device_guided_flash_prompt, name='device_guided_flash_prompt'),
    url(r'^devices/guided/(?P<device_family>[A-Za-z0-9]{1,20})/connection/$', app.setup_views.device_guided_serial_wifi, name='device_guided_serial_wifi'),
    url(r'^devices/guided/mdns/$', app.setup_views.device_guided_find_mdns, name='device_guided_mdns'),
    url(r'^devices/guided/mdns/(?P<mdns_id>[A-Za-z0-9.]{1,60})/$', app.setup_views.device_guided_add_mdns, name='device_guided_add_mdns'),
    url(r'^devices/guided/serial/autodetect/(?P<device_family>[A-Za-z0-9]{1,20})/$', app.setup_views.device_guided_serial_autodetect, name='device_guided_serial_autodetect'),

    ## Other main device views
    url(r'^devices/(?P<device_id>\d{1,20})/control_constants/$', app.views.device_control_constants, name='device_control_constants'),
    url(r'^devices/(?P<device_id>\d{1,20})/dashboard/$', app.views.device_dashboard, name='device_dashboard'),
    url(r'^devices/(?P<device_id>\d{1,20})/dashboard/beer/(?P<beer_id>\d{1,20})/$', app.views.device_dashboard, name='device_dashboard_beer'),
    url(r'^devices/(?P<device_id>\d{1,20})/dashboard/beer/(?P<beer_id>\d{1,20})/annotations.json$', app.views.almost_json_view, name='almost_json_view'),
    # TODO - Implement backlight toggle AJAX API call
    url(r'^devices/(?P<device_id>\d{1,20})/backlight/toggle/$', app.views.device_dashboard, name='device_toggle_backlight'),
    # TODO - Implement temperature control AJAX API calls
    url(r'^devices/(?P<device_id>\d{1,20})/temp_control/$', app.views.device_temp_control, name='device_temp_control'),
    url(r'^devices/(?P<device_id>\d{1,20})/reset/$', app.views.device_eeprom_reset, name='device_eeprom_reset'),
    url(r'^devices/(?P<device_id>\d{1,20})/wifi_reset/$', app.views.device_wifi_reset, name='device_wifi_reset'),
    url(r'^devices/(?P<device_id>\d{1,20})/restart/$', app.views.device_restart, name='device_restart'),
    url(r'^devices/(?P<device_id>\d{1,20})/manage/$', app.views.device_manage, name='device_manage'),
    url(r'^devices/(?P<device_id>\d{1,20})/extended_settings/$', app.views.device_extended_settings, name='device_extended_settings'),
    url(r'^devices/(?P<device_id>\d{1,20})/uninstall/$', app.views.device_uninstall, name='device_uninstall'),

    # Device Utility & Internal Views
    url(r'^devices/(?P<device_id>\d{1,20})/beer/create/$', app.beer_views.beer_create, name='beer_create'),
    url(r'^devices/(?P<device_id>\d{1,20})/beer/status/(?P<logging_status>[A-Za-z0-9]{1,20})/$', app.beer_views.beer_logging_status, name='beer_logging_status'),

    url(r'^devices/(?P<device_id>\d{1,20})/sensors/$', app.views.sensor_list, name='sensor_list'),
    url(r'^devices/(?P<device_id>\d{1,20})/sensors/config/$', app.views.sensor_config, name='sensor_config'),
    url(r'^devices/(?P<device_id>\d{1,20})/sensors/refresh/$', app.views.sensor_refresh, name='sensor_refresh'),

    url(r'^devices/(?P<device_id>\d{1,20})/debug_connection/$', app.views.debug_connection, name='device_debug_connection'),


    # Fermentation Profile Views
    url(r'^fermentation_profile/list/$', app.profile_views.profile_list, name='profile_list'),
    url(r'^fermentation_profile/new/$', app.profile_views.profile_new, name='profile_new'),
    url(r'^fermentation_profile/import/$', app.profile_views.profile_import, name='profile_import'),
    url(r'^fermentation_profile/(?P<profile_id>\d{1,20})/$', app.profile_views.profile_new, name='profile_view'),
    url(r'^fermentation_profile/(?P<profile_id>\d{1,20})/edit/$', app.profile_views.profile_edit, name='profile_edit'),
    url(r'^fermentation_profile/(?P<profile_id>\d{1,20})/delete/$', app.profile_views.profile_delete, name='profile_delete'),
    url(r'^fermentation_profile/(?P<profile_id>\d{1,20})/undelete/$', app.profile_views.profile_undelete, name='profile_undelete'),
    url(r'^fermentation_profile/(?P<profile_id>\d{1,20})/point/(?P<point_id>\d{1,20})/delete$', app.profile_views.profile_setpoint_delete, name='profile_setpoint_delete'),
    url(r'^fermentation_profile/(?P<profile_id>\d{1,20})/csv/$', app.profile_views.profile_points_to_csv, name='profile_points_to_csv'),
    url(r'^fermentation_profile/(?P<profile_id>\d{1,20})/copy/$', app.profile_views.profile_copy, name='profile_copy'),
    url(r'^fermentation_profile/(?P<profile_id>\d{1,20})/rename/$', app.profile_views.profile_rename, name='profile_rename'),
    url(r'^fermentation_profile/(?P<profile_id>\d{1,20})/notes/$', app.profile_views.profile_notes, name='profile_notes'),

    # Beer Views
    url(r'^beer/list/$', app.beer_views.beer_list, name='beer_list'),
    url(r'^beer/(?P<beer_id>\d{1,20})/delete/$', app.beer_views.beer_delete, name='beer_delete'),

    # Api Views
    url(r'^api/lcd/(?P<device_id>\d{1,20})/$', app.api.lcd.getLCD, name="getLCD"),  # For a single device
    url(r'^api/lcd/$', app.api.lcd.getLCDs, name="getLCDs"),  # For all devices/LCDs
    url(r'^api/panel/(?P<device_id>\d{1,20})/$', app.api.lcd.getPanel, name="getPanel"),  # For a single device
    # Read controller log files
    # for the /api/log endpoint, converting to /api/log/<returntype>/<devicetype>/<logtype>/d<device_id>/l<lines>/
    url(r'^api/log/(?P<return_type>text|json)/(?P<device_type>\w{1,20})/(?P<logfile>stdout|stderr)/d(?P<device_id>\d{1,20})/$', app.api.clog.get_device_log_combined, name="get_device_log"),
    url(r'^api/log/(?P<return_type>text|json)/(?P<device_type>\w{1,20})/(?P<logfile>stdout|stderr)/d(?P<device_id>\d{1,20})/l(?P<lines>\d{1,20})/$', app.api.clog.get_device_log_combined, name="get_device_log_lines"),
    url(r'^api/log/(?P<return_type>text|json)/(?P<device_type>\w{1,20})/(?P<logfile>stdout|stderr)/$', app.api.clog.get_device_log_combined, name="get_app_log"),
    url(r'^api/log/(?P<return_type>text|json)/(?P<device_type>\w{1,20})/(?P<logfile>stdout|stderr)/l(?P<lines>\d{1,20})/$', app.api.clog.get_device_log_combined, name="get_app_log_lines"),
    # api/gravity views are located in the gravity app

    # These API endpoints are used by the BrewPi Script Caller
    url(r'^api/devices/$', app.api.devices.get_devices, name="getDevices"),  # To retrieve a BrewPiDevice
    url(r'^api/save_point/$', app.api.devices.create_beer_log_point, name="savePoint"),  # To create a BeerLogPoint

    # Login/Logout Views
    url(r'^accounts/login/$', app.views.login, name='login'),  # This is also settings.LOGIN_URL
    url(r'^accounts/logout/$', app.views.logout, name='logout'),

    # Site-specific views (Help, Settings, etc.)
    url(r'site/settings/$', app.views.site_settings, name="site_settings"),
    url(r'site/help/$', app.views.site_help, name="site_help"),

    path("backups/", include("backups.urls", namespace="backups")),

] + static(settings.DATA_URL, document_root=settings.DATA_ROOT) + \
              firmware_flash.urls.firmware_flash_urlpatterns + gravity.urls.gravity_urlpatterns + \
              external_push.urls.external_push_urlpatterns
# TODO - Convert the above to be properly namespaced

backups/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _


class RestoreUploadFileForm(forms.Form):
    file = forms.FileField()

    def clean_file(self):
        restore_file = self.cleaned_data.get("file",  None)

        if not restore_file:
            raise forms.ValidationError(_("Please upload a restore file"))  # handle empty image
        elif len(str(restore_file)) <= 7:
            raise forms.ValidationError(_("File must have a name longer than 7 characters"))
        elif restore_file.name[-7:] != ".tar.xz":
            raise forms.ValidationError(_("Restore file must be a .tar.xz file"))

        # Note - Because the file isn't written out, we can't test here if the file passed in is actually a valid
        # archive. That test must take place in the view, after the file is written to disk.

        return restore_file

backups/views.py
from typing import Any, Dict

from django.http import HttpRequest, HttpResponse
from django.views.generic import ListView, DetailView, FormView, CreateView, UpdateView, DeleteView
from .models import Backup
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.contrib import messages
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ObjectDoesNotExist
from django.conf import settings
from django_downloadview.views.path import PathDownloadView
from .forms import RestoreUploadFileForm
from django.views.generic.detail import SingleObjectMixin
from django.contrib.auth.mixins import PermissionRequiredMixin

import tarfile

from django.contrib.messages.views import SuccessMessageMixin


# Abstract Views
class ModelCreateView(CreateView):
    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['model'] = self.model
        return context


class ModelUpdateView(UpdateView):
    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['model'] = self.model
        return context


class SuccessMessageDeleteView(DeleteView):
    """Mirrors the functionality of SuccessMessageMixin, but on a DeleteView"""
    success_message = _("Successfully deleted %(object)s")

    def get_success_message(self):
        obj_name = {'object': str(self.get_object())}

        return self.success_message % obj_name

    def post(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        success_message = self.get_success_message()
        if success_message:
            messages.success(self.request, success_message)
        return super().post(request, *args, **kwargs)


# Backup Views
class BackupListView(PermissionRequiredMixin, ListView):
    model = Backup
    permission_required = 'backups.view_backup'


class BackupDetailView(PermissionRequiredMixin, DetailView):
    model = Backup
    permission_required = 'backups.view_backup'


class BackupCreateView(PermissionRequiredMixin, SuccessMessageMixin, ModelCreateView):
    model = Backup
    fields = []
    permission_required = 'backups.add_backup'
    success_message = _("Successfully created backup")

    def form_valid(self, form):
        backup = form.instance
        self.object = backup
        backup.perform_backup()  # TODO - Replace with task
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("backups:backup_detail", kwargs={"pk": self.object.pk})


class BackupDeleteView(PermissionRequiredMixin, SuccessMessageDeleteView):
    model = Backup
    success_url = reverse_lazy('backups:backup_list')
    permission_required = 'backups.delete_backup'
    success_message = _("Successfully deleted backup")


# def upload_file(request):
#     if request.method == 'POST':
#         form = UploadFileForm(request.POST, request.FILES)
#         if form.is_valid():
#             handle_uploaded_file(request.FILES['file'])
#             return HttpResponseRedirect('/success/url/')
#     else:
#         form = UploadFileForm()
#     return render(request, 'upload.html', {'form': form})


class RestoreView(PermissionRequiredMixin, FormView):
    template_name = 'backups/backup_restore.html'
    form_class = RestoreUploadFileForm
    success_url = reverse_lazy('siteroot')
    permission_required = 'backups.restore_backup'  # Custom permission

    def form_valid(self, form):
        """Process the upload and restore the data"""
        restore_file = form.cleaned_data['file']
        output_path = settings.BACKUP_STAGING_DIR.parent / restore_file.name  # Just keep the file name
        with open(output_path, 'wb+') as destination:
            for chunk in restore_file.chunks():
                destination.write(chunk)

        if not tarfile.is_tarfile(output_path):
            output_path.unlink(missing_ok=True)
            messages.error(self.request, _("Restore file must be a valid .tar.xz archive"))
            return redirect(reverse('backups:backup_restore'))

        new_backup, created = Backup.objects.get_or_create(filename_prefix=restore_file.name[:-7])

        new_backup.perform_restore()

        return super().form_valid(form)

    # def get_context_data(self, **kwargs):
    #     """Add the hostname from the request to the context for display"""
    #     context = super().get_context_data(**kwargs)
    #     context['hostname_accessed_at'] = self.request.META['HTTP_HOST']
    #     return context

    # def get_initial(self):
    #     """Returns the initial data to use for forms on this view, as loaded from Constance"""
    #     initial = super().get_initial()
    #     initial['cast_enable'] = config.CAST_ENABLE
    #     initial['cast_hostname'] = config.CAST_HOSTNAME
    #     return initial


class BackupDownloadView(PermissionRequiredMixin, SingleObjectMixin, PathDownloadView):
    model = Backup
    permission_required = 'backups.view_backup'

    def get_path(self):
        """Return path to the linked backup file"""
        object = self.get_object()
        return object.outfile_path

    def get_basename(self):
        object = self.get_object()
        return f"{object.filename_prefix}.tar.xz"


    # def get(self, request, *args, **kwargs):
    #     return super().get(request, *args, **kwargs)

backups/templates/backups/backup_confirm_delete.html
{% extends "sitewide/flat_ui_template.html" %}
{% load custom_tags %}

{% block title %}Delete Backup{% endblock %}

{% block content %}
    <h1>Confirm Deletion</h1>


    <form method="post" action=".">
        {% csrf_token %}

        <h4 class="text-danger">Are you sure you want to delete "{{ object }}"?</h4>

        <div class="row">
            <div class="col-xs-6"><a href="{% url "backups:backup_list" %}" class="btn btn-sm btn-primary">Do Not Delete</a></div>
            <div class="col-xs-6"><input type="submit" class="btn btn-sm btn-danger" value="Confirm"></div>

        </div>

    </form>

{% endblock %}


{% block scripts %}{% endblock %}

backups/templates/backups/backup_detail.html
{% extends "sitewide/flat_ui_template.html" %}
{% load custom_tags %}

{% block title %}Backup Detail{% endblock %}

{% block content %}
    <h1>Backup Detail</h1>

    <h4>Backup: {{ backup }}</h4>

    <p>
        Please download the backup file by clicking the button below and save it somewhere safe in order to be able to
        restore from it at a later date.
    </p>

    <p>
        <a href="{% url 'backups:backup_download' backup.pk %}" class="btn btn-sm btn-primary">Download Backup</a>
    </p>

    <div class="row">
        <div class="col-12">
          <a href="{% url 'backups:backup_delete' backup.pk %}" class="btn btn-sm btn-danger">Delete Backup</a>
        </div>
    </div>

{% endblock %}


{% block scripts %}{% endblock %}

backups/templates/backups/backup_form.html
{% extends "sitewide/flat_ui_template.html" %}
{% load custom_tags %}

{% block title %}{{ view.action|default:"Add" }} Backup{% endblock %}

{% block content %}
    <h1>{{ view.action|default:"Add" }} Backup</h1>


    <div class="row">
        <div class="col-xl-8">
            <form method="post" action="." enctype="multipart/form-data">
              {% csrf_token %}

              <div class="card-body">
                {{ form }}
              </div>

              <p>
                Once a backup is created, a compressed archive will be generated containing the data in the Fermentrack
                database and the files in the data folder - including beer log CSVs. This archive can then be downloaded
                locally for use in restoring Fermentrack at a later point.
              </p>

                <p>
                    <button type="submit" class="btn btn-sm btn-primary">{{ view.action|default:"Add" }} Backup</button>
                </p>
            </form>
        </div>
    </div>


    <p>
        <a href="{% url "backups:backup_list" %}" type="button" class="btn btn-sm btn-success">Return to List</a>
    </p>

{% endblock %}


{% block scripts %}{% endblock %}

backups/templates/backups/backup_list.html
{% extends "sitewide/flat_ui_template.html" %}
{% load custom_tags %}

{% block title %}List Backups{% endblock %}

{% block content %}
    <h1>Available Backups</h1>



    <div class="table-responsive">
      <!-- Backup table -->
      <table class="table align-items-center table-flush">
        <thead class="thead-light">
          <tr>
            <th scope="col">Backup Prefix</th>
            <th scope="col">Created On</th>
          </tr>
        </thead>
        <tbody>
          {% if backup_list %}
            {% for backup in backup_list %}
              <tr>
                <th scope="row">
                  <a href="{% url 'backups:backup_detail' backup.pk %}">{{ backup }}</a>
                </th>
                <td>
                  {{ backup.created }}
                </td>
              </tr>
            {% endfor %}
          {% else %}
              <tr>
                <th scope="row" colspan="2">
                  No Available Backups
                </th>
              </tr>
          {% endif %}
        </tbody>
      </table>
    </div>

    <p>
        <a href="{% url "backups:backup_add" %}" type="button" class="btn btn-sm btn-success">Create New Backup</a>
        <a href="{% url "backups:backup_restore" %}" type="button" class="btn btn-sm btn-default">Restore Backup</a>
    </p>

{% endblock %}


{% block scripts %}{% endblock %}

backups/templates/backups/backup_restore.html
{% extends "sitewide/flat_ui_template.html" %}
{% load custom_tags %}

{% block title %}Restore from Backup{% endblock %}

{% block content %}
    <h1>Restore from Backup</h1>



    <form method="post" action="." enctype="multipart/form-data">
        {% csrf_token %}

        {{ form }}
        <div class="row">
          <p>
            To restore from a previous backup of Fermentrack, select the backup file you have saved locally and
            choose "Restore from Backup" below.
          </p>
          <p>
            NOTE - Restoring from a backup is primarily intended to be done to fresh installations of Fermentrack,
            as existing data will not be deleted from the database. If you restore from a backup into an
            installation of Fermentrack that is already in use, the two data sets will be merged - with data from
            the backup taking precedence over data that already exists in the database.
          </p>
            <p>
                As restored data includes accounts, this may result in you being locked out of your installation of
                Fermentrack. If this happens, simply use the "docker-create-superuser.sh" script in fermentrack-tools
                to regain access.
            </p>
        </div>

        <p>
        <button type="submit" class="btn btn-sm btn-primary">Restore from Backup</button>
        </p>
    </form>

    <p>
        <a href="{% url "backups:backup_list" %}" type="button" class="btn btn-sm btn-success">Return to List</a>
    </p>

{% endblock %}


{% block scripts %}{% endblock %}