backups/urls.py
from django.urls import path

from . import views

app_name = "backups"

urlpatterns = [
    # Backup Views
    path(route='', view=views.BackupListView.as_view(), name='backup_list'),
    path(route='add/', view=views.BackupCreateView.as_view(), name='backup_add'),
    path(route='restore/', view=views.RestoreView.as_view(), name='backup_restore'),
    path(route='view/<int:pk>/', view=views.BackupDetailView.as_view(), name='backup_detail'),
    path(route='delete/<int:pk>/', view=views.BackupDeleteView.as_view(), name='backup_delete'),
    path(route='download/<int:pk>/', view=views.BackupDownloadView.as_view(), name='backup_download'),
    # path(route='update/<slug:slug>/', view=views.BackupUpdateView.as_view(), name='backup_update'),

]

fermentrack_django/urls.py
from django.conf.urls import url
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

import app.views
import app.profile_views
import app.setup_views
import app.beer_views
import app.api.lcd
import app.api.clog
import app.api.devices

import firmware_flash.urls
import gravity.urls
import external_push.urls

admin.autodiscover()

# In addition to urlpatterns below, three paths are mapped by the nginx config file:
# r'^static/' - Maps to collected_static/. Contains collected static files.
# r'^media/' - Maps to media/. Contains uploaded files. Currently unused.
# r'^data/' - Maps to data/. Contains data points collected by brewpi.py.

# Separately, all r'^firmware/' urls are contained in firmware_flash/urls.py

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', app.views.siteroot, name='siteroot'),

    url(r'^upgrade/$', app.views.github_trigger_upgrade, name='github_trigger_upgrade'),
    # url(r'^upgrade/force/$', app.views.github_trigger_force_upgrade, name='github_trigger_force_upgrade'),
    # url(r'^upgrade/delete_lock/$', app.views.delete_upgrade_lock_file, name='delete_upgrade_lock_file'),

    ### Device Views
    url(r'^devices/$', app.views.device_lcd_list, name='device_lcd_list'),
    url(r'^devices/add/$', app.views.add_device, name='device_add'),

    ## New install Guided Setup Views
    url(r'^setup/$', app.setup_views.setup_splash, name="setup_splash"),
    url(r'^setup/add_user/$', app.setup_views.setup_add_user, name="setup_add_user"),
    url(r'^setup/settings/$', app.setup_views.setup_config, name="setup_config"),  # This is settings.CONSTANCE_SETUP_URL

    ## Device Guided Setup Views
    url(r'^devices/guided/$', app.setup_views.device_guided_select_device, name='device_guided_select_device'),
    url(r'^devices/guided/(?P<device_family>[A-Za-z0-9]{1,20})/flash_prompt/$', app.setup_views.device_guided_flash_prompt, name='device_guided_flash_prompt'),
    url(r'^devices/guided/(?P<device_family>[A-Za-z0-9]{1,20})/flash/$', app.setup_views.device_guided_flash_prompt, name='device_guided_flash_prompt'),
    url(r'^devices/guided/(?P<device_family>[A-Za-z0-9]{1,20})/connection/$', app.setup_views.device_guided_serial_wifi, name='device_guided_serial_wifi'),
    url(r'^devices/guided/mdns/$', app.setup_views.device_guided_find_mdns, name='device_guided_mdns'),
    url(r'^devices/guided/mdns/(?P<mdns_id>[A-Za-z0-9.]{1,60})/$', app.setup_views.device_guided_add_mdns, name='device_guided_add_mdns'),
    url(r'^devices/guided/serial/autodetect/(?P<device_family>[A-Za-z0-9]{1,20})/$', app.setup_views.device_guided_serial_autodetect, name='device_guided_serial_autodetect'),

    ## Other main device views
    url(r'^devices/(?P<device_id>\d{1,20})/control_constants/$', app.views.device_control_constants, name='device_control_constants'),
    url(r'^devices/(?P<device_id>\d{1,20})/dashboard/$', app.views.device_dashboard, name='device_dashboard'),
    url(r'^devices/(?P<device_id>\d{1,20})/dashboard/beer/(?P<beer_id>\d{1,20})/$', app.views.device_dashboard, name='device_dashboard_beer'),
    url(r'^devices/(?P<device_id>\d{1,20})/dashboard/beer/(?P<beer_id>\d{1,20})/annotations.json$', app.views.almost_json_view, name='almost_json_view'),
    # TODO - Implement backlight toggle AJAX API call
    url(r'^devices/(?P<device_id>\d{1,20})/backlight/toggle/$', app.views.device_dashboard, name='device_toggle_backlight'),
    # TODO - Implement temperature control AJAX API calls
    url(r'^devices/(?P<device_id>\d{1,20})/temp_control/$', app.views.device_temp_control, name='device_temp_control'),
    url(r'^devices/(?P<device_id>\d{1,20})/reset/$', app.views.device_eeprom_reset, name='device_eeprom_reset'),
    url(r'^devices/(?P<device_id>\d{1,20})/wifi_reset/$', app.views.device_wifi_reset, name='device_wifi_reset'),
    url(r'^devices/(?P<device_id>\d{1,20})/restart/$', app.views.device_restart, name='device_restart'),
    url(r'^devices/(?P<device_id>\d{1,20})/manage/$', app.views.device_manage, name='device_manage'),
    url(r'^devices/(?P<device_id>\d{1,20})/extended_settings/$', app.views.device_extended_settings, name='device_extended_settings'),
    url(r'^devices/(?P<device_id>\d{1,20})/uninstall/$', app.views.device_uninstall, name='device_uninstall'),

    # Device Utility & Internal Views
    url(r'^devices/(?P<device_id>\d{1,20})/beer/create/$', app.beer_views.beer_create, name='beer_create'),
    url(r'^devices/(?P<device_id>\d{1,20})/beer/status/(?P<logging_status>[A-Za-z0-9]{1,20})/$', app.beer_views.beer_logging_status, name='beer_logging_status'),

    url(r'^devices/(?P<device_id>\d{1,20})/sensors/$', app.views.sensor_list, name='sensor_list'),
    url(r'^devices/(?P<device_id>\d{1,20})/sensors/config/$', app.views.sensor_config, name='sensor_config'),
    url(r'^devices/(?P<device_id>\d{1,20})/sensors/refresh/$', app.views.sensor_refresh, name='sensor_refresh'),

    url(r'^devices/(?P<device_id>\d{1,20})/debug_connection/$', app.views.debug_connection, name='device_debug_connection'),


    # Fermentation Profile Views
    url(r'^fermentation_profile/list/$', app.profile_views.profile_list, name='profile_list'),
    url(r'^fermentation_profile/new/$', app.profile_views.profile_new, name='profile_new'),
    url(r'^fermentation_profile/import/$', app.profile_views.profile_import, name='profile_import'),
    url(r'^fermentation_profile/(?P<profile_id>\d{1,20})/$', app.profile_views.profile_new, name='profile_view'),
    url(r'^fermentation_profile/(?P<profile_id>\d{1,20})/edit/$', app.profile_views.profile_edit, name='profile_edit'),
    url(r'^fermentation_profile/(?P<profile_id>\d{1,20})/delete/$', app.profile_views.profile_delete, name='profile_delete'),
    url(r'^fermentation_profile/(?P<profile_id>\d{1,20})/undelete/$', app.profile_views.profile_undelete, name='profile_undelete'),
    url(r'^fermentation_profile/(?P<profile_id>\d{1,20})/point/(?P<point_id>\d{1,20})/delete$', app.profile_views.profile_setpoint_delete, name='profile_setpoint_delete'),
    url(r'^fermentation_profile/(?P<profile_id>\d{1,20})/csv/$', app.profile_views.profile_points_to_csv, name='profile_points_to_csv'),
    url(r'^fermentation_profile/(?P<profile_id>\d{1,20})/copy/$', app.profile_views.profile_copy, name='profile_copy'),
    url(r'^fermentation_profile/(?P<profile_id>\d{1,20})/rename/$', app.profile_views.profile_rename, name='profile_rename'),
    url(r'^fermentation_profile/(?P<profile_id>\d{1,20})/notes/$', app.profile_views.profile_notes, name='profile_notes'),

    # Beer Views
    url(r'^beer/list/$', app.beer_views.beer_list, name='beer_list'),
    url(r'^beer/(?P<beer_id>\d{1,20})/delete/$', app.beer_views.beer_delete, name='beer_delete'),

    # Api Views
    url(r'^api/lcd/(?P<device_id>\d{1,20})/$', app.api.lcd.getLCD, name="getLCD"),  # For a single device
    url(r'^api/lcd/$', app.api.lcd.getLCDs, name="getLCDs"),  # For all devices/LCDs
    url(r'^api/panel/(?P<device_id>\d{1,20})/$', app.api.lcd.getPanel, name="getPanel"),  # For a single device
    # Read controller log files
    # for the /api/log endpoint, converting to /api/log/<returntype>/<devicetype>/<logtype>/d<device_id>/l<lines>/
    url(r'^api/log/(?P<return_type>text|json)/(?P<device_type>\w{1,20})/(?P<logfile>stdout|stderr)/d(?P<device_id>\d{1,20})/$', app.api.clog.get_device_log_combined, name="get_device_log"),
    url(r'^api/log/(?P<return_type>text|json)/(?P<device_type>\w{1,20})/(?P<logfile>stdout|stderr)/d(?P<device_id>\d{1,20})/l(?P<lines>\d{1,20})/$', app.api.clog.get_device_log_combined, name="get_device_log_lines"),
    url(r'^api/log/(?P<return_type>text|json)/(?P<device_type>\w{1,20})/(?P<logfile>stdout|stderr)/$', app.api.clog.get_device_log_combined, name="get_app_log"),
    url(r'^api/log/(?P<return_type>text|json)/(?P<device_type>\w{1,20})/(?P<logfile>stdout|stderr)/l(?P<lines>\d{1,20})/$', app.api.clog.get_device_log_combined, name="get_app_log_lines"),
    # api/gravity views are located in the gravity app

    # These API endpoints are used by the BrewPi Script Caller
    url(r'^api/devices/$', app.api.devices.get_devices, name="getDevices"),  # To retrieve a BrewPiDevice
    url(r'^api/save_point/$', app.api.devices.create_beer_log_point, name="savePoint"),  # To create a BeerLogPoint

    # Login/Logout Views
    url(r'^accounts/login/$', app.views.login, name='login'),  # This is also settings.LOGIN_URL
    url(r'^accounts/logout/$', app.views.logout, name='logout'),

    # Site-specific views (Help, Settings, etc.)
    url(r'site/settings/$', app.views.site_settings, name="site_settings"),
    url(r'site/help/$', app.views.site_help, name="site_help"),

    path("backups/", include("backups.urls", namespace="backups")),

] + static(settings.DATA_URL, document_root=settings.DATA_ROOT) + \
              firmware_flash.urls.firmware_flash_urlpatterns + gravity.urls.gravity_urlpatterns + \
              external_push.urls.external_push_urlpatterns
# TODO - Convert the above to be properly namespaced

app/templates/device_add.html
{% extends "sitewide/flat_ui_template.html" %}
{% load custom_tags %}

{% block title %}Add Device{% endblock %}

{% block content %}

<h1 class="page-header">Add Device</h1>

<form action="{% url "device_add" %}" class="form-horizontal" method="post">{% csrf_token %}

    <div id="deviceConstantsSection">
        <h4 class="form-header">Device Constants</h4>
        {% form_generic form.device_name %}
        {% form_generic form.temp_format %}
        {% form_generic form.data_point_log_interval %}
        {% form_generic form.board_type %}
    </div>


    <div id="inetSocketSection">
        <h4 class="form-header">Connect Interface to Script</h4>
        {% form_generic form.useInetSocket %}

        <div id="localSocketHidden" style="display: none">{# Although I don't recommend local sockets, some people might want them #}
            {% form_generic form.socket_name %}
        </div>

        <div id="inetSocketHidden" style="display: block">
            {% form_generic form.socketHost %}
            {% form_generic form.socketPort %}
        </div>
    </div>


    <div id="connectivitySection">
        <h4 class="form-header">Connect Script to Device</h4>
        {% form_generic form.connection_type %}
        <div id="serialSocketSection" style="display: none"> {# The javascript below will show the relevant section (serial or wifi) #}
                {% form_generic form.serial_port %}
                {% form_generic form.serial_alt_port %}
                {% form_generic form.prefer_connecting_via_udev %}
        </div>

        <div id="wifiSection" style="display: none">
                {% form_generic form.wifi_host %}
                {% form_generic form.wifi_port %}
        </div>
    </div>

    <input type="submit" value="Submit" class="btn btn-primary" />
</form>

{% endblock %}

{% block scripts %}
<script>

function InetSocketHide() {
    if(document.getElementById('id_useInetSocket').checked) {
         document.getElementById('localSocketHidden').style.display = 'none';
         document.getElementById('inetSocketHidden').style.display = '';
    } else {
         document.getElementById('localSocketHidden').style.display = '';
         document.getElementById('inetSocketHidden').style.display = 'none';
    }
}

function ConnectionTypeHide() {
    if(document.getElementById('id_connection_type').options[document.getElementById('id_connection_type').selectedIndex].value == "serial") {
         document.getElementById('wifiSection').style.display = 'none';
         document.getElementById('serialSocketSection').style.display = '';
    } else {
         document.getElementById('wifiSection').style.display = '';
         document.getElementById('serialSocketSection').style.display = 'none';
    }
}


window.onload = function() {
    document.getElementById('id_connection_type').onchange = ConnectionTypeHide;
    document.getElementById('id_useInetSocket').onchange = InetSocketHide;

    {# Above we have the code to handle the toggling as the user completes the form, here we're going to unhide as part of creating the form itself #}
    InetSocketHide();
    ConnectionTypeHide();
};

$(function () {
  $('[data-toggle="tooltip"]').tooltip()
})

</script>

{% endblock %}

app/templates/device_config_new.html
{% extends "sitewide/flat_ui_template.html" %}
{% load custom_tags %}

{# This is the device config page for the "new" (see: master) branch devices.  #}
{# This template is NOT yet implemented #}
{# TODO - Actually convert this to match the new control constants #}


{% block title %}Configure Control Constants{% endblock %}

{% block content %}

<h1 class="page-header">Configure Control Constants</h1>

<form action="{% url "device_config" active_device.id %}" class="form-horizontal" method="post">{% csrf_token %}

    <div id="deviceConstantsSection">
        <h3 class="form-header">Device Constants</h3>
        {% form_generic form.tempSetMin %}
        {% form_generic form.tempSetMax %}
        {% form_generic form.Kp %}
        {% form_generic form.Ki %}
        {% form_generic form.Kd %}
        {% form_generic form.pidMax %}
        {% form_generic form.iMaxErr %}
        {% form_generic form.idleRangeH %}
        {% form_generic form.idleRangeL %}
        {% form_generic form.heatTargetH %}
        {% form_generic form.heatTargetL %}
        {% form_generic form.coolTargetH %}
        {% form_generic form.coolTargetL %}
        {% form_generic form.maxHeatTimeForEst %}
        {% form_generic form.maxCoolTimeForEst %}
        {% form_generic form.beerFastFilt %}
        {% form_generic form.beerSlowFilt %}
        {% form_generic form.beerSlopeFilt %}
        {% form_generic form.fridgeFastFilt %}
        {% form_generic form.fridgeSlowFilt %}
        {% form_generic form.fridgeSlopeFilt %}
    </div>



    <input type="submit" value="Submit" class="btn btn-default" />
</form>

{% endblock %}

{% block scripts %}
<script>

$(function () {
  $('[data-toggle="tooltip"]').tooltip()
})

</script>

{% endblock %}

app/templates/device_debug_connection.html
{% extends "sitewide/flat_ui_template.html" %}{% load static %}
{% load custom_tags %}

{% block title %}Debug Device Connection{% endblock %}

{% block content %}

    <h1>Debugging Connection to {{ active_device.device_name }}</h1>


    <h3>Connection Settings</h3>
    <table class="table table-hover">
        <tr>
            <td>Connection Type</td>
            <td>{{ active_device.connection_type }}</td>
        </tr>

        {% if active_device.connection_type == 'serial' %}
            <tr>
                <td>USB Serial Number</td>
                <td>{{ active_device.udev_serial_number }}</td>
            </tr>

            <tr>
                <td>Locate port via USB Serial?</td>
                <td>{{ active_device.prefer_connecting_via_udev }}</td>
            </tr>

            <tr>
                <td>{% if active_device.prefer_connecting_via_udev %}Last Located {% endif %}Serial Port</td>
                <td>{{ active_device.serial_port }}</td>
            </tr>

            <tr>
                <td>Serial Alt Port (optional)</td>
                <td>{{ active_device.serial_alt_port }}</td>
            </tr>

        {% else %}

            <tr>
                <td>WiFi Hostname</td>
                <td>{{ active_device.wifi_host }}</td>
            </tr>
            <tr>
                <td>WiFi Port</td>
                <td>{{ active_device.wifi_port }}</td>
            </tr>
            <tr>
                <td>Last Cached IP Address (from Hostname)</td>
                <td>{{ active_device.wifi_host_ip }}</td>
            </tr>

        {% endif %}


    </table>



    {% if tests %}
        <h3>Tests Performed</h3>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Test</th>
                    <th>Parameter</th>
                    <th>Pass/Fail</th>
                    <th>Output</th>
                </tr>
            </thead>
        {% for this_test in tests %}
            <tr>
                <td>{{ this_test.name }}</td>
                <td>{{ this_test.parameter }}</td>
                <td>{{ this_test.status }}</td>
                <td>{{ this_test.result }}</td>
            </tr>
        {% endfor %}
        </table>
    {% else %}
        {# If for some reason there aren't any available tests for the device, display a message noting as such. #}
        No connection tests were performed for this device.
    {% endif %}


    <h3>Test Descriptions</h3>
    {# TODO - Update this when we actually add device status management in #}
    <p><b>Device Status Test -</b> Checks that the device status is "active", which is the only status that triggers the Fermentrack process manager to manage BrewPi-script for the device. If this test fails, reset the status to "active" and retry.</p>

    {% if active_device.connection_type == 'serial' %}

    <p><b>Udev Availability Test -</b> Checks that the operating system Fermentrack is running on supports pyudev which enables USB serial number support. If this fails and you want to use the USB serial number to autodetect the correct serial port for a controller, you would need to install a different OS.</p>
    <p><b>USB Serial Number (SN) Usage Test -</b> Checks that the "Prefer connecting via udev" setting is True, thus allowing the device port to be autodetected. If this fails (and you want to use USB serial number support) edit the device to set "Prefer connecting via udev" to true.</p>
    <p><b>USB SN (Serial Number) Test -</b> Checks that the USB serial number is set. If this fails (and you want to use USB serial number support) reinstall the device.</p>
    <p><b>USB SN Availability Test -</b> Checks that there is a device connected with the specified USB serial number. If this fails check the controller's connection to the computer running Fermentrack.</p>
    <p><b>Udev Matches Cached Port Test -</b> Check that the device serial port identifier found when looking up the device by serial number matches the serial port saved in the device cache. If this fails, try disconnecting & reconnecting the controller.</p>





    {% elif active_device.connection_type == 'wifi' %}

    <p><b>DNS Lookup Test -</b> Checks that the device's DNS/mDNS hostname can be resolved. If this test fails, reset the power to the controller and check the WiFi hostname associated with the controller. The current WiFi hostname is displayed in the "parameter" field.</p>
    <p><b>Connection Test -</b> Checks that Fermentrack can connect to the device. If this test fails, the device is unreachable at the address specified in the "Parameter" column. Try restarting or reflashing the device. </p>
    <p><b>Controller Response Test -</b> Checks that the connected controller responds as expected for a BrewPi controller. If this test fails, check the connection strength to the controller and ensure the controller is flashed with the latest firmware.</p>
    <p><b>Cached IP Test -</b> Checks that there is a cached IP address associated with the device. The result of this test can safely be ignored - this value is only used if the DNS lookup test above ever fails.</p>

    {% endif %}

{% endblock %}


{% block scripts %}
{% endblock %}

app/templates/device_mdns_locate.html
{% extends "sitewide/flat_ui_template.html" %}{% load static %}
{% load custom_tags %}

{% block title %}{{ pagetitle }}{% endblock %}

{% block content %}

    <h1>Available (Uninstalled) Devices</h1>

    {% if available_devices %}
        <table>
            <thead>
                <tr> {# TODO - Add tooltips to explain what these mean #}
                    <th>Device Address</th>
                    <th>Board</th>
                    <th>Branch</th>
                    <th>Version</th>
                    <th>Revision</th>
                </tr>
            </thead>
        {% for this_device in available_devices %}
            <tr>
                <td>{{ this_device.mDNSname }}</td>
                <td>{{ this_device.board }}</td>
                <td>{{ this_device.branch }}</td>
                <td>{{ this_device.version }}</td>
                <td>{{ this_device.revision }}</td>
            </tr>
        {% endfor %}
        </table>
    {% else %}
        No uninstalled mDNS BrewPi devices{# TODO - Add some kind of popup or mouseover help text to this message #}
    {% endif %}

    <h1>Available (Active) Installed Devices</h1> {#  TODO - Rephrase this. What I'm trying to say is that the devices are on the network and also are installed #}

    {% if installed_devices %}
        <table>
            <thead>
                <tr> {# TODO - Add tooltips to explain what these mean #}
                    <th>Device Name</th>
                    <th>Device Address</th>
                    <th>Board</th>
                    <th>Branch</th>
                    <th>Version</th>
                    <th>Revision</th>
                </tr>
            </thead>
        {% for this_device in installed_devices %}
            <tr>
                <td>{{ this_device.device.device_name }}</td>
                <td>{{ this_device.mDNSname }}</td> {# For the Arduino implementation, pull this from this_device.device #}
                <td>{{ this_device.board }}</td>
                <td>{{ this_device.branch }}</td>
                <td>{{ this_device.version }}</td>
                <td>{{ this_device.revision }}</td>
            </tr>
        {% endfor %}
        </table>
    {% else %}
        No found mDNS BrewPi devices currently match any devices installed in brewpi-django.
        {# TODO - Add some kind of popup or mouseover help text to this message #}
    {% endif %}

{% endblock %}


{% block scripts %}
{% endblock %}

app/templates/profile_list.html
{% extends "sitewide/flat_ui_template.html" %}
{% load custom_tags %}

{% block title %}{{ pagetitle }}{% endblock %}

{% block content %}
    <h1>Available Fermentation Profiles</h1>{# Is there a better name for this?? #}

    {% if all_profiles %}
        <table class="table">
            <thead>
                <tr>
                    <th>Profile Name</th>
                    <th>Target Points</th>
                    <th>In Use?</th>
                </tr>
            </thead>

            {% for this_profile in all_profiles %}
                <tr>
                    <td><a href="#">{{ this_profile.name }}</a></td>
                    <td>{{ this_profile.fermentationprofilepoint_set.all|length }}</td>
                    <td>{{ this_profile.currently_in_use }}
                        {# TODO - Add an icon here if the profile is active instead of true/false #}
                        {# TODO - Add something here if the profile is pending deletion #}</td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <h2>There are no available fermentation profiles</h2>
    {% endif %}

    <p>{# TODO - Fix the style for the button #}
        <a href="{% url "profile_new" %}" type="button" class="btn btn-sm btn-success">Create New Profile</a>
    </p>

{% endblock %}


{% block scripts %}{% endblock %}

app/templates/site_config.html
{% extends "sitewide/flat_ui_template.html" %}
{% load custom_tags %}

{# I'm converting this form so that it can be used in both the initial guided setup as well as when the user clicks #}
{# the "gear" icon in the upper right of the form #}

{% block title %}App Settings{% endblock %}

{% block content %}

<h1 class="page-header">App Configuration</h1>


        <h3 class="form-header">Configuration Tools</h3>
        <a href="/admin/" class="btn btn-large btn-lg btn-primary">Django Admin Panel</a>
        <a href="{% url 'github_trigger_upgrade' %}" class="btn btn-large btn-lg btn-primary">Update from GitHub</a>

{# Setting this as an include so we can reuse it on our site settings page #}
{% include 'setup/constance_app_configuration.html' %}

{# Load the push targets list template from the external_push app #}
{% include 'external_push/push_target_list_embeddable.html' %}

<h3 class="form-header">Manage Backups</h3>
<p>
    <a href="{% url 'backups:backup_list' %}" class="btn btn-large btn-lg btn-primary">List/Create Backups</a>
    <a href="{% url 'backups:backup_restore' %}" class="btn btn-large btn-lg btn-primary">Restore from Backup</a>
</p>

{% endblock %}

{% block scripts %}
<script>

$(function () {
  $('[data-toggle="tooltip"]').tooltip()
})

</script>
{% endblock %}

app/templates/site_login.html
{% extends "sitewide/flat_ui_template.html" %}

{% block title %}Login{% endblock %}

{% block style %}
    <style type="text/css">


    .form-signin {
    max-width: 600px;
    padding: 19px 29px 29px;
    margin: 0 auto 20px;
    margin-top: 20px;
    background-color: #fff;
    border: 1px solid #e5e5e5;
    -webkit-border-radius: 5px;
    -moz-border-radius: 5px;
    border-radius: 5px;
    -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
    -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
    box-shadow: 0 1px 2px rgba(0,0,0,.05);
    }
    .form-signin .form-signin-heading,
    .form-signin .checkbox {
    margin-bottom: 10px;
    }
    .form-signin input[type="text"],
    .form-signin input[type="password"] {
    font-size: 16px;
    height: auto;
    margin-bottom: 15px;
    padding: 7px 9px;
    }

    </style>

{% endblock %}


{% block content %}

    <form action="{% url "login" %}" method="post" class="form-signin">
    <legend>Log In</legend>
        <fieldset>
            <input type="text" class="input-block-level" name="username" placeholder="Username"/><br />
            <input type="password" class="input-block-level" name="password" placeholder="Password"/><br />
            <input type="hidden" name="posted" value="posted" />{% csrf_token %}{% if next %}
            <input type="hidden" name="next" value="{{ next }}" />{% endif %}
            <button type="submit" class="btn btn-large btn-primary"/>Log In</button><br />
            <span class="help-block"><br>
                <p>Please reach out to a site admin for credentials.</p></span>
        </fieldset>
    </form>

{% endblock %}

app/templates/trigger_requirements_reload.html
{% extends "sitewide/flat_ui_template.html" %}
{% load custom_tags %}
{% load static %}

{% block title %}Reload Python Requirements{% endblock %}

{% block header_scripts %}
{% endblock %}


{% block content %}
    <h1>Reload Python Requirements</h1>

    <p>
        You have triggered a manual reload of the Python packages required by Fermentrack. Please wait several minutes
        for this refresh to complete and for Fermentrack to relaunch before proceeding.
    </p>

    <p>
        Once complete,  you can view the <a href="{% url "get_app_log" "text" "upgrade" "stderr" %}">upgrade log</a> to see
        what was installed/updated.
    </p>


{% endblock %}



{% block scripts %}
{% endblock %}

app/templates/trigger_sqlite_fix.html
{% extends "sitewide/flat_ui_template.html" %}
{% load custom_tags %}
{% load static %}

{% block title %}Trigger Sqlite Fix{% endblock %}

{% block header_scripts %}
{% endblock %}


{% block content %}
    <h1>Trigger SQLite Fix for Django 2.0+</h1>

    <p>
        In between the original version of Django that was used by Fermentrack and modern versions, certain
        backwards-incompatible changes were implemented that can cause issues with SQLite databases. These can be fixed
        programatically, but as we can't automaticaly detect when the version of Django changes we only run this
        command when manually triggered by the user.
    </p>

    <p>
        This command is running now, and may take up to a minute to complete - depending on the size of your SQLite
        database. As soon as the command completes, Fermentrack will restart and you will be able to access it as you
        would normally.
    </p>

    <p><a href="{% url "siteroot" %}">Return to Fermentrack</a></p>

{% endblock %}



{% block scripts %}
{% endblock %}